### ISSUE TITLE
I'd like to help!

### ISSUE THREAD

**Issue by pcasaretto** [felddy/ios-dive-computer#1]
Hi there!

Had the same idea and thought I'd look it up before starting on my own.
I do not own an Ultra yet, and I'm a beginner diver (PADI Open Water with 1 dive logged).
Any plans to give this a go in the near future?

**Comment by felddy** [comment]
Sorry I dropped the ball on replying to this.  This is still very aspirational.  Honestly, it'll probably never get started, but I hope to find a similar project to contribute to.  Thanks for the interest!

**Comment by pcasaretto** [comment]
That’s alright. Let me know if you do find one or decide to start the
project. I’ve investigated some and it seem it would be hard to get Apple
to approve it.

Paulo L F Casaretto
